/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SudokuImport } from './routes/sudoku'

// Create Virtual Routes

const UseDragLazyImport = createFileRoute('/use-drag')()
const TerminalLazyImport = createFileRoute('/terminal')()
const SpeechToTextLazyImport = createFileRoute('/speech-to-text')()
const SlideActionLazyImport = createFileRoute('/slide-action')()
const DialogLazyImport = createFileRoute('/dialog')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const UseDragLazyRoute = UseDragLazyImport.update({
  id: '/use-drag',
  path: '/use-drag',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/use-drag.lazy').then((d) => d.Route))

const TerminalLazyRoute = TerminalLazyImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/terminal.lazy').then((d) => d.Route))

const SpeechToTextLazyRoute = SpeechToTextLazyImport.update({
  id: '/speech-to-text',
  path: '/speech-to-text',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/speech-to-text.lazy').then((d) => d.Route),
)

const SlideActionLazyRoute = SlideActionLazyImport.update({
  id: '/slide-action',
  path: '/slide-action',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/slide-action.lazy').then((d) => d.Route))

const DialogLazyRoute = DialogLazyImport.update({
  id: '/dialog',
  path: '/dialog',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/dialog.lazy').then((d) => d.Route))

const SudokuRoute = SudokuImport.update({
  id: '/sudoku',
  path: '/sudoku',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/sudoku': {
      id: '/sudoku'
      path: '/sudoku'
      fullPath: '/sudoku'
      preLoaderRoute: typeof SudokuImport
      parentRoute: typeof rootRoute
    }
    '/dialog': {
      id: '/dialog'
      path: '/dialog'
      fullPath: '/dialog'
      preLoaderRoute: typeof DialogLazyImport
      parentRoute: typeof rootRoute
    }
    '/slide-action': {
      id: '/slide-action'
      path: '/slide-action'
      fullPath: '/slide-action'
      preLoaderRoute: typeof SlideActionLazyImport
      parentRoute: typeof rootRoute
    }
    '/speech-to-text': {
      id: '/speech-to-text'
      path: '/speech-to-text'
      fullPath: '/speech-to-text'
      preLoaderRoute: typeof SpeechToTextLazyImport
      parentRoute: typeof rootRoute
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalLazyImport
      parentRoute: typeof rootRoute
    }
    '/use-drag': {
      id: '/use-drag'
      path: '/use-drag'
      fullPath: '/use-drag'
      preLoaderRoute: typeof UseDragLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/sudoku': typeof SudokuRoute
  '/dialog': typeof DialogLazyRoute
  '/slide-action': typeof SlideActionLazyRoute
  '/speech-to-text': typeof SpeechToTextLazyRoute
  '/terminal': typeof TerminalLazyRoute
  '/use-drag': typeof UseDragLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/sudoku': typeof SudokuRoute
  '/dialog': typeof DialogLazyRoute
  '/slide-action': typeof SlideActionLazyRoute
  '/speech-to-text': typeof SpeechToTextLazyRoute
  '/terminal': typeof TerminalLazyRoute
  '/use-drag': typeof UseDragLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/sudoku': typeof SudokuRoute
  '/dialog': typeof DialogLazyRoute
  '/slide-action': typeof SlideActionLazyRoute
  '/speech-to-text': typeof SpeechToTextLazyRoute
  '/terminal': typeof TerminalLazyRoute
  '/use-drag': typeof UseDragLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sudoku'
    | '/dialog'
    | '/slide-action'
    | '/speech-to-text'
    | '/terminal'
    | '/use-drag'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sudoku'
    | '/dialog'
    | '/slide-action'
    | '/speech-to-text'
    | '/terminal'
    | '/use-drag'
  id:
    | '__root__'
    | '/'
    | '/sudoku'
    | '/dialog'
    | '/slide-action'
    | '/speech-to-text'
    | '/terminal'
    | '/use-drag'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  SudokuRoute: typeof SudokuRoute
  DialogLazyRoute: typeof DialogLazyRoute
  SlideActionLazyRoute: typeof SlideActionLazyRoute
  SpeechToTextLazyRoute: typeof SpeechToTextLazyRoute
  TerminalLazyRoute: typeof TerminalLazyRoute
  UseDragLazyRoute: typeof UseDragLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  SudokuRoute: SudokuRoute,
  DialogLazyRoute: DialogLazyRoute,
  SlideActionLazyRoute: SlideActionLazyRoute,
  SpeechToTextLazyRoute: SpeechToTextLazyRoute,
  TerminalLazyRoute: TerminalLazyRoute,
  UseDragLazyRoute: UseDragLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/sudoku",
        "/dialog",
        "/slide-action",
        "/speech-to-text",
        "/terminal",
        "/use-drag"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/sudoku": {
      "filePath": "sudoku.tsx"
    },
    "/dialog": {
      "filePath": "dialog.lazy.tsx"
    },
    "/slide-action": {
      "filePath": "slide-action.lazy.tsx"
    },
    "/speech-to-text": {
      "filePath": "speech-to-text.lazy.tsx"
    },
    "/terminal": {
      "filePath": "terminal.lazy.tsx"
    },
    "/use-drag": {
      "filePath": "use-drag.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
